import { LegalPolicyPage, type PolicySection } from "@/components/common/LegalPolicyPage";
import { createMetadata } from "@/lib/metadata";
export const metadata = createMetadata({ title: "Cookie Policy", path: "/cookie-policy" });
const sections: PolicySection[] = [
  { id: "meaning", title: "Cookies and similar technologies", paragraphs: ["Cookies are small values a website asks a browser to store and return on later requests. Local storage and session storage are other browser storage methods. Pixels and analytics scripts can also collect information about visits."] },
  { id: "current-use", title: "Current website practices", paragraphs: ["The website does not include advertising pixels, behavioral advertising, or visitor analytics scripts. It does load Salesforce Embedded Messaging across the site to provide the website agent. That component may use cookies, browser storage, and session identifiers for chat operation, security, and conversation continuity. Their use and duration depend on the Salesforce deployment and your browser settings.", "Form status and interactions are held temporarily in page memory. Enquiry start timestamps are sent as form values. Spam rate limits and career duplicate checks use server memory and do not place browser tracking cookies. The Privacy Policy covers form information and email delivery.", "Hosting or network security services may also process requests and introduce essential browser storage depending on deployment configuration. Development tools are not part of the intended production visitor experience."] },
  { id: "consent", title: "Optional cookies and consent", paragraphs: ["The current application enables no optional analytics or advertising cookies, so it has no optional-cookie consent banner. A privacy checkbox concerns submitted information and is not cookie-tracking consent.", "Before adding optional cookies or comparable tracking, we will update this policy and implement consent controls where required, including rejection and withdrawal choices. Browsing or submitting a form will not be treated as consent to future optional technologies."] },
  { id: "external", title: "External services", paragraphs: ["Resend handles form notifications on the server and is not embedded as a visitor tracking script. External websites you visit through links may set cookies under their own policies. We do not control storage set by those websites."] },
  { id: "controls", title: "Your browser controls", paragraphs: ["Inspect, delete, or block cookies and site storage in your browser's privacy or site settings. Controls differ by device and browser. Blocking essential storage may affect sites that need it. Clearing cookies does not delete a form submission or email already sent to us; use the Privacy Policy's request process for that information."] },
  { id: "updates", title: "Updates and questions", paragraphs: ["We may revise this policy as features or deployment services change. The date identifies the current version. Email contact@cantabridgetechnologies.com about storage questions or a cookie inconsistent with this description, including the cookie name and relevant page."] },
];

export default function CookiePolicyPage() {
  return <LegalPolicyPage title="Cookie Policy" introduction="How the current website uses browser storage and related technologies, and your available choices." sections={sections} />;
}
