import { LegalPolicyPage, type PolicySection } from "@/components/common/LegalPolicyPage";
import { createMetadata } from "@/lib/metadata";
export const metadata = createMetadata({ title: "Terms and Conditions", path: "/terms" });

const sections: PolicySection[] = [
  { id: "scope", title: "Website use and scope", paragraphs: ["These terms govern the Cantabridge Technologies website and its enquiry, consultation, hiring, and careers features. Review them before use. If acting for an organization, you must have authority to supply its information and make the request. Forms are intended for adults aged 18 or older.", "A signed proposal, statement of work, service agreement, employment agreement, or data-processing agreement governs its relevant engagement and takes priority over conflicting website terms for that engagement. Mandatory legal rights remain unaffected."] },
  { id: "information", title: "Information and consultations", paragraphs: ["Service descriptions, examples, case studies, and training information are general information. Features, availability, licensing, integration access, feasibility, price, and dates depend on agreed scope. References to third-party products do not imply endorsement, partnership, or authorization unless expressly stated.", "Submitting a form or joining an initial consultation does not create a service contract, reserve personnel, guarantee response times, promise employment, or commit either party to a project. Initial guidance does not replace a project assessment or independent professional advice. Confirm material requirements in a written agreement before relying on them."] },
  { id: "acceptable-use", title: "Acceptable use", paragraphs: ["Use the site lawfully. Do not impersonate people, submit misleading or unauthorized information, upload malicious files, infringe others' rights, send spam, interfere with systems, bypass protections, or attempt unauthorized access. Intrusive security testing requires our prior written authorization.", "We may reject submissions or restrict access where reasonably needed to address abuse, protect systems or people, comply with law, or maintain the site. This does not remove rights that law requires us to preserve."] },
  { id: "submissions", title: "Submissions and uploaded material", paragraphs: ["You are responsible for accuracy and permission to share submitted material or another person's information. Submit relevant details only. Do not send secrets, credentials, sensitive personal records, or confidential client material through public enquiry forms. Arrange a suitable channel and confidentiality terms first.", "You retain rights in submitted material and permit its use only as reasonably needed to handle your enquiry or application as described in the Privacy Policy. Submission does not transfer ownership of your work. Career applications do not guarantee interviews, offers, or engagements. Do not include work you are prohibited from sharing."] },
  { id: "engagements", title: "Commercial and project terms", paragraphs: ["Scope, deliverables, acceptance, payments, taxes, refunds, cancellation, confidentiality, project intellectual property, warranties, support, and service levels must be agreed separately in writing. The website has no checkout and does not itself create a purchase. Submitting an enquiry does not promise a transfer of project intellectual property.", "Solutions may require third-party licenses, subscriptions, usage charges, and account access. Responsibilities are agreed in the engagement agreement. Scope changes may require revised commercial and delivery terms."] },
  { id: "ownership", title: "Website intellectual property", paragraphs: ["Website text, branding, layouts, and materials belong to Cantabridge Technologies or their owners or licensors. You may view them and make reasonable copies to evaluate our services, subject to applicable law. Reproduction, distribution, sale, or commercial exploitation of protected material requires appropriate permission.", "Third-party trademarks, software, images, and materials remain subject to their owners' rights and licenses. These terms do not confer ownership or a license beyond permitted website use."] },
  { id: "availability", title: "External services and availability", paragraphs: ["External services have their own terms. We do not control their content, security, availability, or policies. Assess them before providing information or purchasing services.", "We may update, maintain, suspend, or discontinue website features. We do not promise uninterrupted access, error-free information, or compatibility with every device. Report material errors for review. Project commitments are governed by the relevant written agreement."] },
  { id: "liability", title: "Disclaimers and limits of responsibility", paragraphs: ["To the extent permitted by law, this informational website is provided on an 'as available' basis without implied warranties of merchantability, fitness for a particular purpose, or uninterrupted availability. Verify information material to your decisions and maintain your device and account security.", "To the extent legally permitted, we are not liable for indirect or consequential losses from website use, including lost business opportunities or anticipated profits. Paid-service responsibility is governed by the engagement agreement. These terms do not impose an unagreed liability cap on a project.", "Nothing excludes or limits liability for fraud, wilful misconduct, or duties and liability that cannot lawfully be excluded, including applicable consumer and personal-data protections. These terms do not waive privacy rights or excuse unlawful handling of information."] },
  { id: "misuse", title: "Claims arising from misuse", paragraphs: ["To the extent permitted by law, you are responsible for third-party claims and reasonable, substantiated direct costs caused by your unlawful website use, unauthorized submissions, or infringement of another person's rights. This applies only to the extent caused by your conduct and not to losses caused by our wrongdoing or breach of law. Claims remain subject to applicable law and a fair opportunity to respond."] },
  { id: "privacy", title: "Privacy and communications", paragraphs: ["The Privacy Policy explains form data, providers, retention, and information requests. The Cookie Policy explains browser storage. Form acknowledgment authorizes use for that form's stated purpose; it is not a blanket waiver or agreement to unrelated marketing.", "We may contact you to handle your request."] },
  { id: "disputes", title: "Governing law and disputes", paragraphs: ["Subject to mandatory laws and rights applicable to you, these website terms are governed by Indian law. Courts of competent jurisdiction in Rajasthan, India, have jurisdiction over website disputes to the extent legally permitted. An engagement agreement may specify its own dispute arrangements.", "Email contact@cantabridgetechnologies.com with concerns so we can try to resolve them. This does not prevent statutory remedies or an application to a competent court, regulator, or consumer forum."] },
  { id: "updates", title: "Updates and interpretation", paragraphs: ["Revisions will display a new date and apply prospectively, without rewriting a signed engagement. We will follow legally required notice or agreement procedures. If a provision is unenforceable, the rest continues to apply to the extent permitted by law. Failure to enforce a provision on one occasion is not a general waiver."] },
];

export default function TermsPage() {
  return <LegalPolicyPage title="Terms and Conditions" introduction="Terms for using our website, sharing enquiries and applications, and exploring Cantabridge Technologies services." sections={sections} />;
}
