export interface Service {
  id: string;
  title: string;
  slug: string;
  shortTitle?: string;
  shortDescription: string;
  description?: string;
  icon?: string;
  image?: string;
  features?: readonly string[];
  benefits?: readonly string[];
  technologies?: readonly string[];
  process?: readonly string[];
  statement?: string;
  useCases?: readonly string[];
  architecture?: readonly string[];
  support?: string;
  faqs?: readonly { question: string; answer: string }[];
  relatedServices?: readonly string[];
  featured: boolean;
  order: number;
  seo?: { title: string; description: string; openGraphTitle?: string; openGraphDescription?: string };
  detailCopy?: {
    heroServiceLabel?: string;
    heroCta?: string;
    heroCtaHref?: string;
    perspectiveParagraphs?: readonly string[];
    deliverablesHeading?: string;
    capabilities?: readonly { title: string; description: string }[];
    projectExamples?: {
      heading: string;
      description: string;
      items: readonly { title: string; description: string }[];
    };
    useCasesLabel?: string;
    useCasesHeading?: string;
    useCasesIntro?: string;
    useCases?: readonly { title: string; description: string; meta: string }[];
    customAgent?: { heading: string; description: string; buttonLabel: string; href?: string };
    architectureLabel?: string;
    architectureHeading?: string;
    architectureIntro?: string;
    architecture?: readonly { title: string; description: string }[];
    outcomesLabel?: string;
    outcomesHeading?: string;
    outcomesIntro?: string;
    outcomes?: readonly { title: string; description: string }[];
    processLabel?: string;
    processHeading?: string;
    process?: readonly { title: string; description: string }[];
    supportHeading?: string;
    supportAreas?: readonly string[];
    faqLabel?: string;
    faqHeading?: string;
    relatedLabel?: string;
    relatedHeading?: string;
    related?: readonly { slug: string; title?: string; description: string }[];
    ctaLabel?: string;
    ctaHeading?: string;
    ctaDescription?: string;
    ctaButton?: string;
    ctaHref?: string;
  };
}
